"""add workout_name to planned_workouts

Revision ID: 2870a78bdeb4
Revises: 
Create Date: 2026-04-03 23:50:27.345055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2870a78bdeb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_workouts', sa.Column('workout_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planned_workouts', 'workout_name')
    # ### end Alembic commands ###
